# Generated by Django 5.1.4 on 2024-12-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicnotification",
            name="file",
        ),
    ]
