# Generated by Django 5.1.4 on 2024-12-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0002_alter_publicnotification_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilsapps",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
