# Generated by Django 5.1.4 on 2024-12-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_order_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
