version: "3"

services:
  django:
    volumes:
      - static_files:/home/app/dj_vpn/staticfiles
    ports:
      - "8000:8000"
    container_name: django_vpn
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ".env"
    depends_on:
      - db

  db:
    container_name: vpn_postgres
    image: postgres:16.6-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${VPS_POSTDB_USER}
      POSTGRES_DB: ${VPS_POSTDB_NAME}
      POSTGRES_PASSWORD: ${VPS_POSTDB_PASSWORD}

  redis:
    container_name: vpn_redis
    image: redis:7.4-alpine
    restart: always
    depends_on:
      - db

  nginx:
    container_name: vpn_nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    image: nginx:1.27-alpine
    volumes:
      - static_files:/vol/
<<<<<<< HEAD
      - ./nginx.conf:/etc/nginx/nginx.conf
=======
>>>>>>> a8216060de05110df38da8ca25c503aa1325822e
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
      - "443:443"
<<<<<<< HEAD
=======
    depends_on:
      - django

  celery:
    container_name: vpn_celery
    build:
      context: .
    restart: always
    entrypoint: celery -A dj_vpn.vpn worker -l INFO
>>>>>>> a8216060de05110df38da8ca25c503aa1325822e
    depends_on:
      - django

#  celery:
#    container_name: vpn_celery
#    build:
#      context: .
#    restart: always
#    command: celery -A dj_vpn.vpn worker -l INFO
#    volumes:
#      - ./:/home/app
#    ports:
#      - "8002:8000"
#    environment:
#      - DEBUG=${DEBUG}
#    depends_on:
#      - redis

volumes:
  postgres_data:
<<<<<<< HEAD
  static_files:
=======
  static_files:
>>>>>>> a8216060de05110df38da8ca25c503aa1325822e
