services:
  django:
    ports:
      - "8000:8000"
    volumes:
      - static_files:/home/app/dj_vpn/staticfiles
    container_name: django_vpn
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ".env"
    depends_on:
      - db

  db:
    container_name: vpn_postgres
    image: postgres:16.6-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

  redis:
    container_name: redis
    expose:
      - 6379
    depends_on:
      - db
    ports:
      - "6380:6379"
    image: redis:7.4-alpine
    restart: always
#    entrypoint: ["sh", "-c", '/home/app/redis_entrypoint.sh', "redis-server"]

  celery:
    container_name: celery
    build:
      context: .
    restart: always
    command: celery -A dj_vpn.vpn.dj_celery worker -l INFO
    ports:
      - "8002:8000"
    environment:
      - DEBUG=${DEBUG}
    depends_on:
      - redis

  nginx:
    container_name: vpn_nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    image: nginx:1.27-alpine
    volumes:
      - static_files:/vol/
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "8080:80"
#      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
  static_files:
