# Generated by Django 5.1.4 on 2024-12-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentdevice",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="privatenotification",
            name="file",
        ),
        migrations.AddField(
            model_name="contentdevice",
            name="is_blocked",
            field=models.BooleanField(default=True, help_text="بلاک شدن"),
        ),
    ]
