# Generated by Django 5.1.4 on 2025-01-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentdevice",
            name="last_connected",
        ),
    ]
