# Generated by Django 5.1.4 on 2025-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="volume",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="volume_usage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
