# Generated by Django 5.1.4 on 2024-12-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_contentdevice_deleted_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestLog",
        ),
    ]
