# Generated by Django 5.1.4 on 2024-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_requestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentdevice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
