# Generated by Django 5.1.4 on 2025-01-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_number_of_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="start_premium",
            field=models.DateTimeField(
                blank=True, help_text="تاریخ شروع اشتراک", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="number_of_days",
            field=models.PositiveIntegerField(
                blank=True, help_text="تعداد روز", null=True
            ),
        ),
    ]
