# Generated by Django 5.1.4 on 2025-01-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_start_premium_alter_user_number_of_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="number_of_login",
            field=models.PositiveIntegerField(
                blank=True, editable=False, help_text="تعداد لاگین های کاربر", null=True
            ),
        ),
    ]
