# Generated by Django 5.1.4 on 2025-01-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_number_of_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number_of_login",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                editable=False,
                help_text="تعداد لاگین های کاربر",
                null=True,
            ),
        ),
    ]
