# Generated by Django 5.1.4 on 2025-01-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_number_of_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number_of_login",
            field=models.PositiveIntegerField(
                db_default=0, editable=False, help_text="تعداد لاگین های کاربر"
            ),
        ),
    ]
