# Generated by Django 5.1.4 on 2025-01-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_number_of_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentdevice",
            name="is_connected",
        ),
        migrations.AddField(
            model_name="contentdevice",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("normal_user", "Normal User"),
                    ("premium_user", "Premium User"),
                ],
                default="normal_user",
                help_text="نوع اکانت",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="accounts_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("limit", "Limit"),
                    ("expired", "Expired"),
                    ("nothing", "Nothing"),
                ],
                default="nothing",
                help_text="",
                max_length=15,
            ),
        ),
    ]
