# Generated by Django 5.1.4 on 2025-01-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_contentdevice_is_connected_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentdevice",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="user",
            name="accounts_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("limit", "Limit"),
                    ("expired", "Expired"),
                    ("nothing", "Nothing"),
                ],
                default="nothing",
                help_text="",
                max_length=15,
            ),
        ),
    ]
