# Generated by Django 5.1.4 on 2025-01-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_contentdevice_last_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_connected_user",
            field=models.BooleanField(
                default=False,
                help_text="این فیلد مشخص میکنه که کاربر ایا به کانفیگش متصل شده هست یا خیر",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="accounts_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("limit", "Limit"),
                    ("expired", "Expired"),
                    ("nothing", "Nothing"),
                ],
                default="nothing",
                help_text="",
                max_length=15,
            ),
        ),
    ]
