# Generated by Django 5.1.4 on 2025-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_is_connected_user_alter_user_accounts_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="volume_choice",
            field=models.CharField(
                choices=[("mg", "Mg"), ("gb", "Gb"), ("tra", "Tra")],
                default="gb",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="accounts_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("limit", "Limit"),
                    ("expired", "Expired"),
                    ("nothing", "Nothing"),
                ],
                default="nothing",
                help_text="active --> حجم و تاریخ انتقضای کانفینگ کاربر فعال هسنن \nlimit --> لیمیت یعنی کاربر حجمش تموم شده هست \nexpire --> یعنی کاربر روز کانفینگ ان تموم شده هست",
                max_length=15,
            ),
        ),
    ]
