# Generated by Django 5.1.4 on 2025-01-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_volume_choice_alter_user_accounts_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="volume_choice",
            field=models.CharField(
                choices=[
                    ("nothing", "Nothing"),
                    ("mg", "Mg"),
                    ("gb", "Gb"),
                    ("tra", "Tra"),
                ],
                default="gb",
                max_length=7,
            ),
        ),
    ]
