# Generated by Django 5.1.4 on 2025-01-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_user_options_alter_user_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="volume",
            field=models.PositiveIntegerField(blank=True, db_default=0, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="volume_usage",
            field=models.PositiveIntegerField(blank=True, db_default=0, null=True),
        ),
    ]
