# Generated by Django 5.1.4 on 2025-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_user_volume_alter_user_volume_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="volume",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="volume_usage",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
