# Generated by Django 5.1.4 on 2025-03-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct", "مستقیم"),
                    ("tunnel", "تانل"),
                    ("tunnel_direct", "تانل و دایرکت"),
                ],
                help_text="you can choice --> tunnel - direct - tunnel_direct",
                max_length=14,
                null=True,
            ),
        ),
    ]
