# Generated by Django 5.1.4 on 2025-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number_of_login",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                editable=False,
                help_text="تعداد لاگین های کاربر",
            ),
        ),
    ]
