# Generated by Django 5.1.4 on 2025-01-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_number_of_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="accounts_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("limit", "Limit"),
                    ("expired", "Expired"),
                    ("nothing", "Nothing"),
                ],
                default="expired",
                help_text="active --> حجم و تاریخ انتقضای کانفینگ کاربر فعال هسنن \nlimit --> لیمیت یعنی کاربر حجمش تموم شده هست \nexpire --> یعنی کاربر روز کانفینگ ان تموم شده هست",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="number_of_days",
            field=models.PositiveIntegerField(help_text="تعداد روز"),
        ),
        migrations.AlterField(
            model_name="user",
            name="start_premium",
            field=models.DateField(
                blank=True, help_text="تاریخ شروع اشتراک", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="volume",
            field=models.PositiveIntegerField(),
        ),
    ]
