# Generated by Django 5.1.4 on 2025-02-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_user_accounts_status_alter_user_number_of_days_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("a_user", "a user"), ("b_user", "b user")], null=True
            ),
        ),
    ]
