# Generated by Django 5.1.8 on 2025-04-19 18:26

import dj_vpn.cores.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'user_login_log',
            },
        ),
        migrations.DeleteModel(
            name='RecycleUser',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', dj_vpn.cores.managers.UserSoftManager()),
            ],
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_login_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
