# Generated by Django 5.1.4 on 2025-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("a_user", "a user"), ("b_user", "b user")],
                null=True,
            ),
        ),
    ]
