# Generated by Django 5.1.4 on 2025-02-20 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="all_volume_usage",
            field=models.FloatField(
                default=0,
                editable=False,
                help_text="کاربر تا الان چقدر حجم مصرف کرده!",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
