# Generated by Django 5.1.4 on 2025-02-20 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_all_volume_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_inf_volume",
            field=models.BooleanField(
                default=False, help_text="ایا حجم کاربر نامحدود باشد!"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="volume",
            field=models.PositiveIntegerField(
                help_text="کاربر چقدر حجم داشته باشد",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
