# Generated by Django 5.1.4 on 2025-02-20 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_is_inf_volume_alter_user_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="start_premium",
            field=models.DateField(
                blank=True,
                help_text="تاریخ شروع اشتراک اگر کاربر لاگین کند اشتراک کاربر از همان روز شروع خواهد شد",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="volume",
            field=models.PositiveIntegerField(
                default=0,
                help_text="کاربر چقدر حجم داشته باشد",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
