# Generated by Django 5.1.4 on 2025-02-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_start_premium_alter_user_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number_of_days",
            field=models.PositiveIntegerField(help_text="تعداد روز", null=True),
        ),
    ]
