# Generated by Django 5.1.4 on 2025-02-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_number_of_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number_of_days",
            field=models.PositiveIntegerField(
                default=0, help_text="تعداد روز", null=True
            ),
        ),
    ]
