# Generated by Django 5.1.4 on 2025-02-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_number_of_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("direct", "مستقیم"), ("tunnel", "تانل")],
                null=True,
            ),
        ),
    ]
