# Generated by Django 5.1.4 on 2025-02-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct", "مستقیم"),
                    ("tunnel", "تانل"),
                    ("tunnel_direct", "تانل و دایرکت"),
                ],
                null=True,
            ),
        ),
    ]
