# Generated by Django 5.1.4 on 2025-01-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="is_active",
            field=models.BooleanField(default=True, help_text="قابل نمایش"),
        ),
    ]
