# Generated by Django 5.1.4 on 2025-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0002_config_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="config_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tunnel_server", "سرور تانل"),
                    ("direct_server", "سرور مستقیم"),
                ],
                max_length=14,
                null=True,
            ),
        ),
    ]
