# Generated by Django 5.1.4 on 2025-02-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0003_config_config_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="config_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tunnel", "سرور تانل"),
                    ("direct", "سرور مستقیم"),
                    ("tunnel_direct", "سرور تانل و دایرکت"),
                ],
                max_length=14,
                null=True,
            ),
        ),
    ]
