# Generated by Django 5.1.4 on 2024-12-31 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, editable=False, null=True),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True, help_text="نام دامنه", max_length=255
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, help_text="بلاک بودن دامنه"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="قابل نمایش"),
                ),
            ],
            options={
                "db_table": "domain",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, editable=False, null=True),
                ),
                (
                    "country_name",
                    models.CharField(
                        db_index=True,
                        help_text="Names of countries in English",
                        max_length=255,
                    ),
                ),
                (
                    "ir_country_name",
                    models.CharField(
                        db_index=True,
                        help_text="نام کشورها به صورت فارسی",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="قابل نمایش"),
                ),
                (
                    "country_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="عکس کشور",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="country_image",
                        to="cores.images",
                    ),
                ),
            ],
            options={
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, editable=False, null=True),
                ),
                ("config", models.TextField(help_text="کانفینگ")),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("vmess", "Vmess"),
                            ("vless", "Vless"),
                            ("trojan", "Trojan"),
                            ("shadosocks", "Shadosocks"),
                            ("tls", "Tls"),
                            ("open_vpn", "Open Vpn"),
                            ("wire_guard", "Wire Guard"),
                            ("ikev2", "Ikev2"),
                            ("l2tp", "L2Tp"),
                            ("sstp", "Sstp"),
                            ("pptp", "Pptp"),
                            ("soft_ether", "Soft Ether"),
                            ("open_connect", "Open Connect"),
                        ],
                        help_text="پروتوکول های فیلترشکن",
                    ),
                ),
                ("is_free", models.BooleanField(default=False, help_text="رایگان")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="قابل نمایش"),
                ),
                (
                    "price",
                    models.FloatField(blank=True, help_text="قیمت کانفیگ", null=True),
                ),
                ("volume", models.PositiveIntegerField(help_text="حجم کانفینگ")),
                (
                    "country",
                    models.ForeignKey(
                        help_text="کشور مورد نظر",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="country_configs",
                        to="configs.country",
                    ),
                ),
            ],
            options={
                "db_table": "config",
            },
        ),
    ]
