# Generated by Django 5.1.4 on 2024-12-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
