# Generated by Django 5.1.4 on 2024-12-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="user",
        ),
    ]
