# Generated by Django 5.1.4 on 2024-12-29 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0002_alter_config_deleted_at_alter_country_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="country_name",
            field=models.CharField(
                db_index=True, help_text="Names of countries in English", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="ir_country_name",
            field=models.CharField(
                db_index=True, help_text="نام کشورها به صورت فارسی", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="duration",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="max_connect_device",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="volume",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
