# Generated by Django 5.1.4 on 2024-12-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0003_country_is_active_alter_country_country_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
