# Generated by Django 5.1.4 on 2024-12-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0004_config_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
