# Generated by Django 5.1.4 on 2024-12-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, editable=False, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="image_height",
                        upload_to="images/%Y/%m/%d",
                        width_field="image_width",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        help_text="توضیحی برای تصویر خود بگذارید",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("image_size", models.PositiveIntegerField(blank=True, null=True)),
                ("image_width", models.PositiveIntegerField(blank=True, null=True)),
                ("image_height", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "images",
            },
        ),
    ]
