# Generated by Django 5.1.4 on 2024-12-31 07:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, editable=False, null=True),
                ),
                ("coupon_code", models.CharField(max_length=50, unique=True)),
                (
                    "max_used",
                    models.PositiveIntegerField(
                        help_text="چند نفر میتوانند از این کد تخفیف استفاده کنند",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "number_of_used",
                    models.PositiveIntegerField(
                        default=0, help_text="تعداد افراد استفاده از این کد تخفیف"
                    ),
                ),
                ("expired_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[("is_percent", "درصد"), ("is_value", "مقدار")],
                        verbose_name="نوع کد تخفیف",
                    ),
                ),
                (
                    "coupon_price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="مقدار کد تخفیف",
                    ),
                ),
                (
                    "min_value",
                    models.FloatField(
                        blank=True,
                        help_text="این فیلد میتوانید مشخص کنید که هر خرید حداقل چه چقدر باشه که بتوان از این کد تخفیف استفاده کرد",
                        null=True,
                        verbose_name="حداقل قیمت",
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True,
                        help_text="در این فیلد میتوان مشخص کرد که حداکثر تخفیف به اینکد چقدر باشه",
                        null=True,
                        verbose_name="حداکثر قیمت",
                    ),
                ),
            ],
            options={
                "db_table": "coupons",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, editable=False, null=True),
                ),
                ("is_percent", models.BooleanField(default=False)),
                ("is_value", models.BooleanField(default=False)),
                (
                    "amount",
                    models.FloatField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config",
                    models.ForeignKey(
                        limit_choices_to={"is_free": False},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configs.config",
                    ),
                ),
            ],
            options={
                "db_table": "discounts",
            },
        ),
        migrations.CreateModel(
            name="UserConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, editable=False, null=True),
                ),
                (
                    "volume_usage",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("volume", models.PositiveIntegerField()),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="config_subscription",
                        to="configs.config",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
    ]
