# Generated by Django 5.1.4 on 2024-12-29 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0002_remove_plan_user"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="config",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="config_subscription",
                to="configs.config",
            ),
            preserve_default=False,
        ),
    ]
