# Generated by Django 5.1.4 on 2024-12-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coupon",
        ),
        migrations.AlterField(
            model_name="userconfig",
            name="volume_usage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
    ]
