# Generated by Django 5.1.4 on 2024-12-29 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0002_alter_coupon_deleted_at_alter_discount_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="amount",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
